services:
  - type: web
    name: telegram-media-bot
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: ""
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
